# frozen_string_literal: true

module SpellLists
  ARCANE_BY_LEVEL = {
    1 => [
      "Arcane Armor",
      "Auditory Illusion",
      "Beguile Humanoid",
      "Blinding Flash",
      "Chameleon",
      "Choking Grip",
      "Conjure Cacodemon Spa",
      "Counterspell",
      "Desiccate",
      "Discern Gist",
      "Discern Magic",
      "Earth's Excrescence",
      "Faithful Companion",
      "Fan of Flames",
      "Frighten Humanoid",
      "Ice Floe",
      "Illumination*",
      "Illusory Figment",
      "Infuriate Humanoid",
      "Kindle Flame",
      "Leaping",
      "Mage Missile",
      "Seal Portal",
      "Sharpness",
      "Shatter Blade",
      "Silent Step",
      "Slicing Blow",
      "Slickness",
      "Sling Stone",
      "Slumber",
      "Spider Climbing",
      "Summon Manes",
      "Thunderclap",
      "Unliving Puppet",
      "Wall of Smoke",
      "Weave Smoke",
    ],
    2 => [
      "Adjust Self",
      "Battering Ram",
      "Bewitch Humanoid",
      "Bloody Flux",
      "Burning Sparks",
      "Circling Winds",
      "Conjure Imp",
      "Conjure Petty Elemental",
      "Dark Whisper",
      "Deathless Minion",
      "Discern Invisible",
      "Dominate Humanoid",
      "Earth's Wave",
      "Energy Protection",
      "Frostbite",
      "Gale of Wind",
      "Halt Humanoids",
      "Hypnotic Sigil",
      "Illusory Duplicates",
      "Illusory Interior",
      "Levitation",
      "Locate Object",
      "Magic Lock",
      "Necromantic Potence",
      "Ogre Strength",
      "Phantasmal Figment",
      "Physical Protection",
      "Rain of Vitriol",
      "Shrouding Fog",
      "Sudden Staircase",
      "Summon Insect Swarm",
      "Sunflare",
      "Swimming",
      "Vitriolic Infusion",
      "Warp Wood",
      "Webbing",
    ],
    3 => [
      "Avian Messenger",
      "Bewitch Crowd",
      "Boil Blood",
      "Chimerical Figment",
      "Clairaudiency",
      "Clairvoyancy",
      "Cone of Frost",
      "Conjure Hellion",
      "Create Chasm",
      "Deflect Ordinary Missiles",
      "Dismember",
      "Dispel Magic Pro",
      "Dominate Monster",
      "Earth's Teeth",
      "Fireball",
      "Flight",
      "Force of Impetus",
      "Growth*",
      "Ice Sheet",
      "Illumination, Perpetual",
      "Inaudibility",
      "Incite Madness",
      "Infuriate Crowd",
      "Invisibility",
      "Lightless Vision",
      "Lightning Strike",
      "Rune of Warding",
      "Skinchange",
      "Speak with Dead",
      "Spellward",
      "Strengthen the Unliving",
      "Summon Hellhounds",
      "Thunderbolt",
      "Wall of Thunder",
      "Water Breathing",
      "Weave Fire",
    ],
    4 => [
      "Animate Undead",
      "Arcane Shift",
      "Bewitch Monster",
      "Cloud of Poison",
      "Conjure Incubus",
      "Conjure Major Elemental",
      "Earth's Tremor",
      "Energy Invulnerability",
      "Cone of Fear",
      "Flesh to Ash",
      "Giant Strength",
      "Growth, Plant*",
      "Guise Self",
      "Halt Monsters",
      "Hidden Host",
      "Illusory Terrain",
      "Indiscernibility",
      "Inferno",
      "Iron Maiden",
      "Locate Treasure",
      "Magic Carpet",
      "Physical Invulnerability",
      "Safe Travels",
      "Scouring Zephyr",
      "Scry",
      "Shrieking Skull",
      "Slumber, Deep",
      "Spectral Figment Spellward Other",
      "Sphere of Invulnerability, Lesser",
      "Summon Shadow",
      "Sunder Structure",
      "Telepathy",
      "Wall of Flame",
      "Wall of Frost",
      "Weave Water",
    ],
    5 => [
      "Blast Ward",
      "Capsizing Wave",
      "Carnage",
      "Circle of Agony",
      "Cone of Paralysis",
      "Conjure Dybbuk",
      "Conjure Supreme Elemental",
      "Contact Other Sphere",
      "Control Winds",
      "Curse of the Swine",
      "Deflect Ordinary Weapons Pro",
      "Dominate Plants",
      "Earth's Mire*",
      "Fillet and Serve",
      "Firestorm",
      "Flay the Slain",
      "Forest Enchantment",
      "Forgetfulness",
      "Guise Other",
      "Ice Storm",
      "Lay of the Land",
      "Life Transfer",
      "Lightless Vision, Mass",
      "Locate Haunting",
      "Mirage",
      "Phantasmal Horror",
      "Rouse the Fallen",
      "Selective Fire",
      "Soul Swap",
      "Spectral Legion",
      "Summon Ooze",
      "Summon Weather",
      "Telekinesis",
      "Teleportation",
      "Wall of Stone",
      "X-Ray Vision",
    ],
    6 => [
      "Anti-Magic Sphere Pro",
      "Banner of Invincibility",
      "Body Swap",
      "Clairaudiency, Greater",
      "Clairvoyancy, Greater",
      "Conflagration",
      "Conjure Fiend",
      "Conjure Genie",
      "Control Weather",
      "Disfigure Body and Soul",
      "Disintegration",
      "Earth's Movement",
      "Enslave Humanoid",
      "Level Water",
      "Locate Distant Object",
      "Locate Place of Power",
      "Madness of Crowds",
      "Necromantic Invulnerability",
      "Panic",
      "Passageway",
      "Perpetual Figment",
      "Petrification*",
      "Programmatic Figment",
      "Quest",
      "Reveal Ritual Magic",
      "Soul Eating",
      "Spellwarded Zone",
      "Sphere of Invulnerability, Greater",
      "Summon Invisible Stalker",
      "Torpor",
      "Transform Other",
      "Transform Self",
      "Trollblood",
      "Wall of Annihilation",
      "Wall of Corpses",
      "Wall of Force",
    ],
  }.freeze

  DIVINE_BY_LEVEL = {
    1 => [
      "Allure",
      "Angelic Choir",
      "Bane-Rune",
      "Call of the Wolf",
      "Counterspell",
      "Cure Light Injury*",
      "Delay Disease",
      "Destroy Dead",
      "Discern Evil*",
      "Discern Gist",
      "Discern Magic",
      "Discern Poison",
      "Faithful Companion",
      "Frighten Beast",
      "Holy Circle*",
      "Illumination*",
      "Infuriate Beast",
      "Kindle Flame",
      "Locate Animal or Plant",
      "Pass Without Trace",
      "Predict Weather",
      "Purify Food and Water*",
      "Remove Fear*",
      "Salving Rest",
      "Sanctuary",
      "Seal Portal",
      "Shatter Blade",
      "Sling Stone",
      "Unliving Puppet",
      "Word of Command",
    ],
    2 => [
      "Augury",
      "Beguile Humanoid",
      "Bewitch Beast",
      "Call of the Wolf Pack",
      "Choking Grip",
      "Circling Winds",
      "Cure Moderate Injury*",
      "Dark Whisper",
      "Deathless Minion",
      "Delay Poison",
      "Discern Bewitchment*",
      "Divine Armor",
      "Divine Grace",
      "Dominate Beasts",
      "Energy Protection",
      "Halt Humanoids",
      "Holy Blessing*",
      "Holy Chant",
      "Magic Lock",
      "Necromantic Potence",
      "Noiselessness",
      "Physical Protection",
      "Righteous Wrath",
      "Shimmer",
      "Slicing Blow",
      "Slumber",
      "Speak with Beasts",
      "Spiritual Weapon",
      "Swift Sword",
      "Transform Beast",
    ],
    3 => [
      "Avian Messenger",
      "Bewitch Humanoid",
      "Call of the Wild Bear",
      "Clairaudiency",
      "Clairvoyancy",
      "Cure Blindness*",
      "Cure Disease*",
      "Cure Major Injury*",
      "Deflect Ordinary Missiles Pro",
      "Discern Curse*",
      "Discern Invisible",
      "Dispel Magic",
      "Divine Protection",
      "Growth, Beast",
      "Holy Circle, Sustained*",
      "Holy Prayer",
      "Illumination, Perpetual*",
      "Invulnerability to Evil*",
      "Lightning Strike",
      "Phantasmal Figment",
      "Remove Curse*",
      "Rune of Warding",
      "Speak with Dead",
      "Spellward",
      "Strengthen the Unliving",
      "Striking",
      "Swift Sword, Sustained",
      "Water Breathing",
      "Water Walking",
      "Winged Flight",
    ],
    4 => [
      "Angelic Aura",
      "Call of the Galloping Herd",
      "Call of the Regal Pride",
      "Crafting",
      "Create Water",
      "Cure Serious Injury*",
      "Death Ward",
      "Dismember",
      "Divination",
      "Energy Invulnerability",
      "Gale of Wind",
      "Growth",
      "Inaudibility",
      "Indiscernibility",
      "Inspire Awe*",
      "Invisibility",
      "Lightless Vision",
      "Neutralize Poison*",
      "Physical Invulnerability",
      "Protection from Temperature",
      "Repair Disfigurement & Dis.*",
      "Skinchange",
      "Smite Undead*",
      "Snakes to Staffs*",
      "Speak with Plants",
      "Spellward Other",
      "Sphere of Invulnerability, Lesser",
      "Spirit of Healing*",
      "Sunflare",
      "Tongues",
    ],
    5 => [
      "Atonement",
      "Blast Ward",
      "Boil Blood",
      "Call of the Great Cats",
      "Communion",
      "Cone of Fear",
      "Control Winds",
      "Create Food",
      "Cure Critical Injury*",
      "Curse of the Swine",
      "Deflect Ordinary Weapons",
      "Dominate Monster",
      "Fate",
      "Fiery Pillar",
      "Giant Strength",
      "Growth, Plant",
      "Guise Self",
      "Healing Circle",
      "Lay of the Land",
      "Locate Haunting",
      "Restore Life and Limb*",
      "Safe Travels",
      "Scry",
      "Spiritwalk",
      "Strength of Mind*",
      "Summon Insect Plague",
      "Sword of Fire",
      "True Seeing",
      "Turn to Dust",
      "Vigor",
    ],
    6 => [
      "Anti-Magic Sphere",
      "Arrows of the Sun",
      "Banner of Invincibility",
      "Barrier of Blades",
      "Bath of the Goddess",
      "Bewitch Monster",
      "Blast Ward, Greater",
      "Call of the Ancient Tusk",
      "Call of the Aerophract Steeds",
      "Clairaudiency, Greater",
      "Clairvoyancy, Greater",
      "Dispel Evil*",
      "Fillet and Serve",
      "Flesh to Ash",
      "Guise Other",
      "Hidden Host",
      "Home Ward",
      "Illusory Terrain",
      "Level Water",
      "Locate Place of Power",
      "Phoenix Aura",
      "Prophetic Dream",
      "Quest",
      "Salvific Rain",
      "Slumber, Deep",
      "Spectral Figment",
      "Spellward Zone",
      "Sphere of Invulnerability, Greater",
      "Summon Weather",
      "Summon Winged Herald",
    ],
  }.freeze

  GNOSTIC_BY_LEVEL = {
    1 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
    2 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
    3 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
    4 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
    5 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
    6 => [
      "Invocation of the Mountain’s Bones",
      "Invocation of the Eternal Forge",
      "Invocation of the Iron Crucible",
      "Invocation of the Open Gate",
      "Invocation of the Maker’s Fire",
    ],
  }.freeze
end
